server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/HotelMicroDB
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

