server:
  port: 8083

spring:
  application:
    name: RATING-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/RatingService
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: configserver:http://localhost:8085






